### ISSUE TITLE
Relación entre campos de un formulario

### ISSUE THREAD

**Issue by isamaima** [humano/milfs#15]
Buenas tardes. Sería bueno que en un formulario yo pudiera relacionar los campos. Es decir, que si por ejemplo tengo los campos departamento y ciudad, el campo ciudad muestre las opciones según lo que seleccione en departamento. O por ejemplo que si selecciono un ítem cualquiera en un campo, con base en este me seleccione automáticamente valores por defecto en otros campos.

**Comment by humano** [comment]
Hola.
Te refieres aun combo, pues buenas noticias, ya estoy en ello, mira una prueba de concepto en http://datos.labmde.org/milfs/?id=1 en el campo Municipio de Colombia.
Gracias por tus sugerencias

**Comment by isamaima** [comment]
Hola, gracias por responder. Bueno, por ahí es la cosa, gracias. Sin embargo, acá me imagino que las dos listas que tengo en Municipio de colombia se me reportan como un único campo no?. Me refiero más a relacionar campos (predefinidos) entre sí. Supongamos que tengo un campo "Lugar" y un campo "Mapa", que cuando seleccione un lugar (el nombre), él me cargue por defecto el punto en el mapa. Gracias.

**Comment by humano** [comment]
Bueno, ese es otro caso de uso diferente que no está por ahora en mi hoja de ruta, ya que voy desarrollando a medida que necesito los diferentes casos de uso, sin embargo algo como eso se podría hacer por medio de la api, pero en todo caso necesita programación.

**Comment by isamaima** [comment]
Comprendo, gracias!

**Comment by humano** [comment]
Espero que en un futuro se pueda implementar.
