### ISSUE TITLE
Problema de actualización

### ISSUE THREAD

**Issue by kleper** [humano/milfs#17]
Actualice una de las instancias mas viejas que tengo de MILFS y no funciona ninguna de las nuevas funciones como el timeline.php o la galeria.php 

Tengo los siguientes errores:

[Thu Jun 04 00:39:43.047404 2015] [:error] [pid 221] [client 10.10.10.1:46314] PHP Warning:  require(milfs/xajax/xajax.inc.php): failed to open stream: No such file or directory in /home/ServerWEB/www/milfs/timeline.php on line 5
[Thu Jun 04 00:39:43.047470 2015] [:error] [pid 221] [client 10.10.10.1:46314] PHP Fatal error:  require(): Failed opening required 'milfs/xajax/xajax.inc.php' (include_path='.:/usr/share/php:/usr/share/pear') in /home/ServerWEB/www/milfs/timeline.php on line 5

Encontré que esta base de datos no tenia la tabla de parametrización entonces la cree y cree un estilo para el formulario 2 
http://www.bibliolabs.cc/milfs/timeline.php?id=2

**Comment by humano** [comment]
Recuerda que el timeline.php debe estar un nivel por encima del directorio milfs o en su defecto cambiar los path a los archivos que incluye.

**Comment by kleper** [comment]
En esta instancia no lo puedo tener un nivel arriba, entonces hice la prueba cambiando los path ya se ve mejor pero aun sale esto:

[Thu Jun 04 06:48:58.310163 2015] [:error] [pid 4175] [client 10.10.10.1:50317] PHP Notice:  Use of undefined constant id_campo - assumed 'id_campo' in /home/ServerWEB/www/milfs/funciones/funciones.php on line 1372, referer: http://www.bibliolabs.cc/milfs/timeline.php?id=2
[Thu Jun 04 06:48:58.310190 2015] [:error] [pid 4175] [client 10.10.10.1:50317] PHP Notice:  Use of undefined constant id_campo - assumed 'id_campo' in /home/ServerWEB/www/milfs/funciones/funciones.php on line 1373, referer: http://www.bibliolabs.cc/milfs/timeline.php?id=2
