### ISSUE TITLE
Archivo milfs.sql.gz no carga bien usando phpmyadmin

### ISSUE THREAD

**Issue by brolin** [humano/milfs#19]
La última versión de este archivo no me funcionó en el import a través phpmyadmin. Parece que está corrupto porque no logro descomprimirlo. Usé una versión anterior extraída del repositorio y el import fue exitoso.

**Comment by humano** [comment]
Gracias por avisar, se corrigió en este commit https://github.com/humano/milfs/commit/8a37a0f0a63d2c07d2cd0084fcb563c9241762d2 el caul es importante para que funcionen los nuevos tipos de campo combo-select y relación.
