### ISSUE TITLE
Problemas con UPLOAD

### ISSUE THREAD

**Issue by kleper** [humano/milfs#24]
En una instancia en la que uso https tengo el problema que no puedo importar, dice que no puede subir el archivo al servidor con el siguiente error:

Error ! - El Archivo (../tmp/73134fe4221f5b8b57d2a5bc8c3bea63.csv) no llegó al servidor
Importando formulario (6)

Cree la carpeta ../tmp pero no lo logra.

Errores del servidor web:

n /home/serverweb/datos/milfs/funciones/funciones.php on line 4112, referer: https://datos.karisma.org.co/milfs/index.php
[Tue Jul 07 13:41:25 2015] [error] [client 181.48.119.154] FastCGI: server "/usr/lib/cgi-bin/php5-fcgi" stderr: PHP message: PHP Notice:  Undefined index:  in /home/serverweb/datos/milfs/funciones/funciones.php on line 4112, referer: https://datos.karisma.org.co/milfs/index.php
[Tue Jul 07 13:41:28 2015] [error] [client 181.48.119.154] FastCGI: server "/usr/lib/cgi-bin/php5-fcgi" stderr: PHP message: PHP Warning:  Missing argument 3 for formulario_campos_select() in /home/serverweb/datos/milfs/funciones/funciones.php on line 2429, referer: https://datos.karisma.org.co/milfs/index.php
[Tue Jul 07 13:41:29 2015] [error] [client 181.48.119.154] FastCGI: server "/usr/lib/cgi-bin/php5-fcgi" stderr: PHP message: PHP Warning:  Missing argument 5 for matriz_formulario() in /home/serverweb/datos/milfs/funciones/funciones.php on line 2230, referer: https://datos.karisma.org.co/milfs/index.php
[Tue Jul 07 13:41:29 2015] [error] [client 181.48.119.154] FastCGI: server "/usr/lib/cgi-bin/php5-fcgi" stderr: PHP message: PHP Notice:  Undefined index: campo_filtro in /home/serverweb/datos/milfs/funciones/funciones.php on line 2238, referer: https://datos.karisma.org.co/milfs/index.php
[Tue Jul 07 13:41:29 2015] [error] [client 181.48.119.154] FastCGI: server "/usr/lib/cgi-bin/php5-fcgi" stderr: PHP message: PHP Warning:  mysql_real_escape_string() expects parameter 1 to be string, array given in /home/serverweb/datos/milfs/funciones/funciones.php on line 2240, referer: https://datos.karisma.org.co/milfs/index.php
[Tue Jul 07 13:41:29 2015] [error] [client 181.48.119.154] FastCGI: server "/usr/lib/cgi-bin/php5-fcgi" stderr: PHP message: PHP Notice:  Undefined index: campo_filtro in /home/serverweb/datos/milfs/funciones/funciones.php on line 2242, referer: https://datos.karisma.org.co/milfs/index.php
[Tue Jul 07 13:41:29 2015] [error] [client 181.48.119.154] FastCGI: server "/usr/lib/cgi-bin/php5-fcgi" stderr: PHP message: PHP Warning:  Missing argument 5 for remplacetas(), called in /home/serverweb/datos/milfs/funciones/funciones.php on line 2246 and defined in /home/serverweb/datos/milfs/funciones/funciones.php on line 2411, referer: https://datos.karisma.org.co/milfs/index.php
[Tue Jul 07 13:41:31 2015] [error] [client 181.48.119.154] FastCGI: server "/usr/lib/cgi-bin/php5-fcgi" stderr: PHP message: PHP Warning:  Missing argument 1 for formularios_muestra_listado(), called in /home/serverweb/datos/milfs/funciones/funciones.php on line 1896 and defined in /home/serverweb/datos/milfs/funciones/funciones.php on line 1851, referer: https://datos.karisma.org.co/milfs/index.php
[Tue Jul 07 13:41:31 2015] [error] [client 181.48.119.154] FastCGI: server "/usr/lib/cgi-bin/php5-fcgi" stderr: PHP message: PHP Notice:  Undefined variable: formulario in /home/serverweb/datos/milfs/funciones/funciones.php on line 1853, referer: https://datos.karisma.org.co/milfs/index.php
[Tue Jul 07 13:41:31 2015] [error] [client 181.48.119.154] FastCGI: server "/usr/lib/cgi-bin/php5-fcgi" stderr: PHP message: PHP Notice:  Undefined variable: resultado in /home/serverweb/datos/milfs/funciones/funciones.php on line 1862, referer: https://datos.karisma.org.co/milfs/index.php
[Tue Jul 07 13:41:31 2015] [error] [client 181.48.119.154] FastCGI: server "/usr/lib/cgi-bin/php5-fcgi" stderr: PHP message: PHP Notice:  Undefined variable: formulario in /home/serverweb/datos/milfs/funciones/funciones.php on line 1896, referer: https://datos.karisma.org.co/milfs/index.php
[Tue Jul 07 13:41:32 2015] [error] [client 181.48.119.154] FastCGI: server "/usr/lib/cgi-bin/php5-fcgi" stderr: PHP message: PHP Notice:  Undefined variable: resultado in /home/serverweb/datos/milfs/funciones/funciones.php on line 1843, referer: https://datos.karisma.org.co/milfs/index.php
[Tue Jul 07 13:41:32 2015] [error] [client 181.48.119.154] FastCGI: server "/usr/lib/cgi-bin/php5-fcgi" stderr: PHP message: PHP Notice:  Undefined variable: resultado in /home/serverweb/datos/milfs/funciones/funciones.php on line 1880, referer: https://datos.karisma.org.co/milfs/index.php
[Tue Jul 07 13:41:37 2015] [error] [client 181.48.119.154] FastCGI: server "/usr/lib/cgi-bin/php5-fcgi" stderr: PHP message: PHP Notice:  Undefined variable: perfil_nombre in /home/serverweb/datos/milfs/funciones/funciones.php on line 1909, referer: https://datos.karisma.org.co/milfs/index.php
[Tue Jul 07 13:41:37 2015] [error] [client 181.48.119.154] FastCGI: server "/usr/lib/cgi-bin/php5-fcgi" stderr: PHP message: PHP Notice:  Undefined variable: resultado in /home/serverweb/datos/milfs/funciones/funciones.php on line 1910, referer: https://datos.karisma.org.co/milfs/index.php
[Tue Jul 07 13:41:37 2015] [error] [client 181.48.119.154] FastCGI: server "/usr/lib/cgi-bin/php5-fcgi" stderr: PHP message: PHP Warning:  fopen(tmp/e14013b174c5c23e6d39d7147d3ba1d4.csv): failed to open stream: No such file or directory in /home/serverweb/datos/milfs/funciones/funciones.php on line 1915, referer: https://datos.karisma.org.co/milfs/index.php

**Comment by humano** [comment]
Ese upload se realiza desde un iframe similar al de subir imágenes y otros
de MILFS.
Revisa eso y trata de aplicar la misma solución que le aplicaste a los
otros.

**Comment by kleper** [comment]
Es diferente, en los otros archivos se agregaba:
//$xajax = new xajax();
$xajax = new xajax("https://datos.karisma.org.co/milfs/index.php");

Pero el de uploads no tiene eso.

**Comment by kleper** [comment]
El problema es en el archivo de funciones en la linea 1915 
Aparece asi: $nombre = "tmp/$filename";
Lo cambie por: $nombre = "/tmp/$filename";

Y listo

**Comment by kleper** [comment]
Creo que en general tenemos muchos problemas si decidimos usar HTTPS hay que cambiar demasiados archivos de forma manual, y esto deberia de estar parametrizado, en este momento no puedo usar el mapa y ya cambie varios archivos en mi instancia en https pero no logro resolverlo. :(

**Comment by humano** [comment]
Bien. Es necesario resolver todos los problemas y documentarlos para hacer
la parametrización.

**Comment by kleper** [comment]
Creo que no hay mucho que documentar para que funcione en HTTPS. Por lo visto toca cambiar en todos los archivos en donde aparezca:

$xajax = new xajax();

Cambiarlo por:

$xajax = new xajax("https://DOMINIO/milfs/index.php");

Eso lo resuelve, aunque la parte del mapa ni idea.

**Comment by kleper** [comment]
Para dar soporte para instalaciones en conexiones seguras (HTTPS) se debe asegurar que todos los recursos que usa la aplicación se conecten a recursos https, ejemplo, en mapa.php
La llamada a la libreria de leafleft la hace en http://cdn.leafletjs.com/leaflet-0.7/leaflet.js
Para que funcione en https hay que cambiarla a https://cdn.leafletjs.com/leaflet-0.7/leaflet.js
Esto se puede hacer de forma permanente para todas las partes que usen librerias externas, si se llaman de una vez en https no afecta las instancias no seguras y no se vuelve un problema para las instancias que se instalen en https.

**Comment by humano** [comment]
Corregido en el último upload
