### ISSUE TITLE
Visualizacion de imagenes

### ISSUE THREAD

**Issue by kleper** [humano/milfs#40]
En el archivo de funciones.php en la linea 2073 se declara la función:
if($row[id_campo] =='0'){       $contenido = strip_tags($contenido);            }
                $campo[$row[id_campo]]=$contenido;

Es la encargada de que las imágenes se vean en algunas visualizaciones como la de linea de tiempo, como se llama el id_campo  si en los campos uno tiene otro campo imágenes que tiene otro ID por ahora la solución es agregar otra linea donde se defina el id del campo que sea tipo imagen que este utilizando ejemplo:

if($row[id_campo] =='155'){       $contenido = strip_tags($contenido);            }
                $campo[$row[id_campo]]=$contenido;

**Comment by humano** [comment]
Resuelto en la nueva versión. Por favor confirmar.
