### ISSUE TITLE
Milfs Multiempresa

### ISSUE THREAD

**Issue by kleper** [humano/milfs#41]
Hasta el momento empezamos a probar las opciones "multiempresa" de milfs, pero toda su configuración se debe hacer de manera manual.

### Problemas encontrados en relación con la versión actual.

 * La nueva forma de agrupar las áreas muestra las áreas en todas las empresas debería ser para cada empresa. Lo mismo pasa con los formularios, aunque no muestra los formularios de otras "empresas" muestra los grupos seria bueno solo mostrar las correspondientes a cada empresa.

### Creación de empresas y de usuarios para empresa.

En este momento toda la configuración multiempresa es manual y debe hacerse editando directamente en la base de datos. seria bueno en un futuro tener un super admin, que permita la creación de empresas y de asignar usuarios a las empresas, y tener usuarios multiempresa.

**Comment by humano** [comment]
Se han hecho algunas mejoras en la multiempresa, abrir un issue para el manejador de empresas.
