### ISSUE TITLE
Problemas con consultas, importación de datos y exportación de datos

### ISSUE THREAD

**Issue by kleper** [humano/milfs#44]
Estas son algunas fallas que se están presentando en las instancias actualizadas recientemente:

## Consultas
 
Cuando se realizan consultas y el formulario que tiene campos URL, cuando muestra la URL genera unos puntos suspensivos al final que dañan la url y cuando se le da click lo envía una url inexistente, ejemplo:

https://www.dropbox.com/home/Public?preview=Captura+de+pantalla+de+2015-07-21+13-24-18.png

## Importación:

Cuando se intenta importar la plataforma dice que no puede subir al servidor el archivo csv, es como sino encontrara la carpeta a donde debe subir los archivos, he tenido que modificar el archivo de upload.php para especificar la carpeta tmp

## Exportación:

Cuando se quieren exportar los datos de un formulario parece que la plataforma no esta copiando el archivo para descargar a una carpeta que esté accesible desde el servidor web, he revisado y el archivo se genera en la carpeta /tmp pero no se mueve a un lugar en donde se puede descargar.

https://www.dropbox.com/home/Public?preview=Captura+de+pantalla+de+2015-07-21+13-24-37.png

**Comment by humano** [comment]
Por favor separa cada caso en un inssue para revisarlos.
