### ISSUE TITLE
Georeferenciación

### ISSUE THREAD

**Issue by kleper** [humano/milfs#45]
Como se puede hacer para que los campos tipo "mapa" capturen la ubicación desde un teléfono android o desde el navegador web?

**Comment by humano** [comment]
La función estaba implementada pero fue comentada.por problemas.
Se puede revisar, no es muy complejo es un javascript que funciona con los
datos del browser.

**Comment by kleper** [comment]
Chevere si la podemos probar de nuevo, como se activa? o que hay que actualizar?, es para un par de cosas que quiero hacer con la gente de NN y seria muy útil.

**Comment by humano** [comment]
ya lo implemente en http://datos.labmde.org/milfs/?id=30
pruebalo y me avisas para subirlo al github

2015-07-22 16:03 GMT-05:00 Kleper <notifications@github.com>:

> Chevere si la podemos probar de nuevo, como se activa? o que hay que
> actualizar?, es para un par de cosas que quiero hacer con la gente de NN y
> seria muy útil.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/humano/milfs/issues/45#issuecomment-123862823>.
>



-- 
#====#
 |___|__\___
 | _ |   |_ |      }
 "(_)""  ""(_)"

Twitter: @fredy_rivera

Phone USA:  (347) 688-4473

Mobil telephone: +57 3044886255

**Comment by kleper** [comment]
Lo probé y funcionó al segundo intento, aunque el primero intento fue decirle al celular que permitiera compartir la ubicación con la web.

**Comment by humano** [comment]
Bien. Ese es el caso de uso esperado. El usuario siempre tiene que
autorizar la geolocalizacion.

**Comment by kleper** [comment]
Perfecto. Gracias.

Enviado desde mi calculadora análoga.

**Comment by humano** [comment]
corregido
