### ISSUE TITLE
Exportación / Importanción

### ISSUE THREAD

**Issue by kleper** [humano/milfs#47]
En este momento hay un problema con el tema de la exportación y la importación de formularios que vimos estos días, escribo acá para tenerlo como recordatorio para resolverlo. :)

**Comment by humano** [comment]
Corregido en la ultima actualización, se debe para instalaciones anteriores se debe crear el directorio milfs/tmp/ y darle con el www-data o similar de propietario y con permisos de escritura sobre el.
