### ISSUE TITLE
Consultas: filtrar búsquedas por grupos de formularios

### ISSUE THREAD

**Issue by mariajulianayb** [humano/milfs#49]
En **Consultas** poder filtrar también por **Grupos de Formularios**.

**Comment by humano** [comment]
Por favor especifica mejor el caso de uso, no entiendo lo que quieres, el área de consultas trabaja con los datos de un formulario, quieres que se muestre en consulta los datos de varios formularios a la vez?

**Comment by humano** [comment]
NO hubo respuesta, cierro esta entrada.
