### ISSUE TITLE
Markdown

### ISSUE THREAD

**Issue by kleper** [humano/milfs#54]
Al parecer el markdown no esta funcionando probe con los campos tipo HTML y tipo nota en donde cargaba normalmente el editor de MK y ahora no carga y tampoco lo esta interpretando en los campos en donde estaba.

**Comment by humano** [comment]
Marcado como pesadilla
El Markdown se visualiza en los form embebidos y los campos HTML solo hacen render de codigo html, no de MD.
Chao!
