### ISSUE TITLE
Formularios Embebidos

### ISSUE THREAD

**Issue by kleper** [humano/milfs#55]
cuando se llena un formulario
http://nn.labmde.org/milfs/?form=5
usando los formularios embebidos no sale el boton para llenar otro formulario
quizá haga algo como pasarle parámetros por la url del embebido se muestre o no un boton para que haga eso.

**Comment by humano** [comment]
Esa es la función esperada de los formularios embebidos, sin embargo esa acción se puede controlar desde la pagina que llama el embebido, no obstante estoy considerando parar algunos parámetros a los embebidos por la url, eso quizá se haga próximamente

**Comment by humano** [comment]
Se mejoraron los formularios embebidos, ya se puede llenar sucesivamente.
