### ISSUE TITLE
Parametrización Iconos

### ISSUE THREAD

**Issue by kleper** [humano/milfs#57]
Creo que seria muy util implementar la función de subir los iconos en la misma herramienta en el momento que se le estan colocando los iconos a las categorias para no tener que subir los iconos a otro servidor. Hacerlo más para usuarios. :)

**Comment by humano** [comment]
Puedes subir los iconos como imágenes en un formulario y luego copiar las
urls en el parametrización de categorías de los iconos.
:)

2015-11-05 18:21 GMT-05:00 Kleper <notifications@github.com>:

> Creo que seria muy util implementar la función de subir los iconos en la
> misma herramienta en el momento que se le estan colocando los iconos a las
> categorias para no tener que subir los iconos a otro servidor. Hacerlo más
> para usuarios. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/humano/milfs/issues/57>.
>



-- 
#====#
 |___|__\___
 | _ |   |_ |      }
 "(_)""  ""(_)"

Twitter: @fredy_rivera

Phone USA:  (347) 688-4473

Mobil telephone: +57 3044886255

**Comment by kleper** [comment]
Me lo sospeche desde un principio. :P Pero no es algo trivial, lo ideal es hacer la menor cantidad de re procesos posibles.

**Comment by humano** [comment]
Costo beneficio no creo que esto se priorice.
Chao !
