### ISSUE TITLE
Campo Separador o titulo

### ISSUE THREAD

**Issue by kleper** [humano/milfs#61]
En ocasiones en la creación de formularios que tienen muchos campos es necesario crear un separados que tengo un nombre o titulo, con el propósito de agrupar preguntas o tipos de pregunta, es útil para encuestas o recolección de datos de investigaciones.

**Comment by humano** [comment]
Para eso son las "Areas" cuando se crean los campos, la separación por áreas es funcional en los formularios embebidos, aun no en formularios modales.
