### ISSUE TITLE
Consultas

### ISSUE THREAD

**Issue by kleper** [humano/milfs#62]
En el nuevo modulo de consultas lo de exportar no funciona, se queda patinando.
[Wed Nov 11 21:57:30.790539 2015] [:error] [pid 3726] [client 190.159.67.128:58232] PHP Notice:  Undefined variable: imagen in /var/www/nn/milfs/funciones/funciones.php on line 225, referer: http://nn.labmde.org/milfs/index.php
[Wed Nov 11 21:57:30.790833 2015] [:error] [pid 3726] [client 190.159.67.128:58232] PHP Fatal error:  Call to undefined function str_get_html() in /var/www/nn/milfs/funciones/funciones.php on line 253, referer: http://nn.labmde.org/milfs/index.php

**Comment by humano** [comment]
Corregido, hay varios archivos para actualizar.
