### ISSUE TITLE
api simple no ordena bien

### ISSUE THREAD

**Issue by mcanet** [humano/milfs#63]
El api simple no devuelve ordenado por tiempo las respuestas y como tampoco tiene timestamp incluido es impossible ordenarlo temporalmente: http://datos.casatrespatios.org/milfs/api.php?id=22&tipo=simple

**Comment by humano** [comment]
El json está ordenado por timestamp DESC 
En la última actualización se agregaron algunos metadatos incluido el timestamp.
Para mejor control de la api, use la versión completa
. http://datos.casatrespatios.org/milfs/api.php?id=22

**Comment by kleper** [comment]
Como esta ordenada la API Simple?

**Comment by humano** [comment]
Estaba haciendo un ordenamiento por control, acabo de corregirla para que ordene por timestamp descendente.
Revisa y si funciona cierras este issue.
}

**Comment by kleper** [comment]
Listo, Resuelto., Gracias.
