### ISSUE TITLE
Problema en datos.php

### ISSUE THREAD

**Issue by kleper** [humano/milfs#64]
Estuve revisando un problema con la visualización de imagenes cuando se suben a milfs, el problema tiene que ver con la siguiente variable en datos.php

$url = "http://www.bibliolabs.cc/milfs/";

Si la url no tiene / al final cuando se sube la imagen no se ve, pero si se agrega el / al final se empiezan a crear direcciones con un // ejemplo: http://www.bibliolabs.cc/milfs//map.php?id=42
En algunos navegadores direcciones con // no cargan.

**Comment by humano** [comment]
La variable en datos debe quedar $url = "http://www.bibliolabs.cc/milfs/";
algunas correcciones hay que hacerlas en la plantilla, las del codigo las revisaré.

**Comment by humano** [comment]
Ya quedó corregido el bug del / extra al llamar mapa.php
