### ISSUE TITLE
Areas de los campos

### ISSUE THREAD

**Issue by kleper** [humano/milfs#66]
Creo que esa funcionalidad no sirve, entorpece el trabajo y no permite ordenar los campo, me gasto tiempo diciendo en el formulario el orden de los campo pero por lo de las areas no lo respeta. tampoco se esta respetando el orden de las areas, y no se esta guardando el area del campo y hay que volversela a poner cada que se modifica el area.

**Comment by humano** [comment]
Corregí el bug que no permitia asignar un area en la creacion del campo
