### ISSUE TITLE
Errores varios

### ISSUE THREAD

**Issue by kleper** [humano/milfs#69]
Veo muchos warning y notice que sale cuando se esta haciendo cualquier cosa en MILFS, creo que vale la pena revisarlos:

Notice: Undefined variable: opciones in /var/www/datos/index.php on line 134

Warning: Missing argument 4 for formulario_areas(), called in /var/www/datos/milfs/funciones/funciones.php on line 4061 and defined in /var/www/datos/milfs/funciones/funciones.php on line 3114

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Notice: Undefined variable: control_respuesta in /var/www/datos/milfs/funciones/funciones.php on line 3244

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Notice: Use of undefined constant control - assumed 'control' in /var/www/datos/milfs/funciones/funciones.php on line 3903

Notice: Undefined variable: valor_actual in /var/www/datos/milfs/funciones/funciones.php on line 3912

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Notice: Undefined variable: resultado in /var/www/datos/milfs/funciones/funciones.php on line 8612

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Notice: Undefined variable: id_empresa in /var/www/datos/index.php on line 148

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Notice: Undefined variable: id_empresa in /var/www/datos/index.php on line 149

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Notice: Undefined variable: id_empresa in /var/www/datos/index.php on line 150

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Notice: Undefined variable: id_empresa in /var/www/datos/index.php on line 151

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Notice: Undefined variable: id_empresa in /var/www/datos/index.php on line 152

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Notice: Undefined variable: id_empresa in /var/www/datos/index.php on line 153

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Notice: Undefined variable: id_empresa in /var/www/datos/index.php on line 154

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Notice: Undefined variable: id_empresa in /var/www/datos/index.php on line 155

Warning: include(includes/datos.php): failed to open stream: No such file or directory in /var/www/datos/milfs/funciones/conex.php on line 5

Warning: include(): Failed opening 'includes/datos.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/datos/milfs/funciones/conex.php on line 5

Notice: Undefined variable: id_empresa in /var/www/datos/index.php on line 156

Notice: Use of undefined constant site - assumed 'site' in /var/www/datos/index.php on line 166

Notice: Use of undefined constant REQUEST_URI - assumed 'REQUEST_URI' in /var/www/datos/index.php on line 166

**Comment by humano** [comment]
Revisé el código para corregir esos errores, por favor revisa si aparecen otros o se cierra este issue.
