### ISSUE TITLE
Llenado de Formularios

### ISSUE THREAD

**Issue by kleper** [humano/milfs#71]
Cuando se esta creando un formulario desde la interfaz administrativa de MILFS y se le da llenar, envia a la siguiente URL: http://datos.labmde.org/?form=26 pero no abre el formulario para edicion, lo mismo pasa con http://datos.labmde.org/f31 solo funciona si quieres editar un formulario con http://datos.labmde.org/g31

**Comment by humano** [comment]
Corregido
