### ISSUE TITLE
Problema de registro de Tupale.co en Vivaldi

### ISSUE THREAD

**Issue by son0p** [humano/milfs#72]
No sé si sea problema de MILFS pero:

Se intentó registrar varias veces un nuevo usuario desde el navegador Vivaldi (con flash deshabilitado) y la pagina se queda esperando infinitamente.

El registro en Firefox no se queda bloqueado esperando, salta a la pantalla principal de Tupale.co pero no llega el correo de confirmación, ni tampoco se activa el usuario

----------------
Vivaldi	1.0.435.42 () (64-bit)
Revision	575538bc320e213510be1e66f3521382e615129d
OS	Linux 
Blink	537.36 (@0)
JavaScript	V8 4.9.385.33
Flash	(Disabled)

**Comment by kleper** [comment]
Hola,
El problema es que el registro de usuario por el boton de "Login" no esta funcionando bien desde hace meses, se esta en un proceso de migración para resolver eso.
