### ISSUE TITLE
Buscador / Visualizador Publico

### ISSUE THREAD

**Issue by kleper** [humano/milfs#8]
Una herramienta que permita enviar un link a diferentes personas para que puedan ver los datos ingresados en un formulario y que permita filtro, puede ser algo parecido a lo que hizo para lo de los verbos pero que se le puedan aplicar filtros

**Comment by kleper** [comment]
Referencias:

http://d3js.org/

https://www.elastic.co/

http://okfnlabs.org/

http://okfnlabs.org/projects/data-explorer/

http://okfnlabs.org/projects/retrato-da-violencia/

**Comment by humano** [comment]
Suena como algo que es mejor hacerlo usando la api json del MILFS
