### ISSUE TITLE
Camel Case

### ISSUE THREAD

**Issue by kleper** [humano/milfs#9]
La plataforma necesita poder tener mayúsculas sostenidas, o Camel Case y diferentes usos de mayúsculas en la escritura.

**Comment by humano** [comment]
Hay un par de funciones que capitalizan los nombres de los campos combinando 
$campo_nombre = ucfirst(strtolower($campo_nombre));  dejar -> comentar esa linea
if($v !='') {$v = ucfirst(strtolower($v));  dejar -> if($v !='') {$v = $v; 

Y también una que convierte en mayúsculas los titulos de los formularios 
$placeholder = strtoupper(limpiar_caracteres($campo)); dejar -> $placeholder = limpiar_caracteres($campo);
y 
$title = strtoupper(limpiar_caracteres($campo)); dejar -> $title = limpiar_caracteres($campo);
Si se modifican esas funciones podrás usar indiscriminadamente mayúsculas y minúsculas.
